spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/augustana_hub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop # Drops + recreates on startup AND drops on shutdown

#      Early Production/Testing
#      ddl-auto: create-drop # Attempts to alter tables without deleting data
    show-sql: true
